"""add some tables

Revision ID: 05f490c80f7c
Revises: 8900d94366d0
Create Date: 2024-12-24 23:36:40.595028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05f490c80f7c'
down_revision = '8900d94366d0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oog_customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_eng', sa.String(length=100), nullable=True),
    sa.Column('name_chn', sa.String(length=100), nullable=True, comment='maybe there is no chinese name, just let it equals to english name'),
    sa.Column('region', sa.String(length=200), nullable=True, comment='the localtion of headquarters. like China HK, China Taiwan, Japan etc.'),
    sa.Column('web_site', sa.String(length=200), nullable=True),
    sa.Column('detail_info', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='a company of our company group can be a customer. but need to add new customer to represent it.'
    )
    op.create_table('oog_company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_eng', sa.String(length=50), nullable=True),
    sa.Column('name_chn', sa.String(length=50), nullable=True, comment='maybe there is no chinese name, just let it equals to english name'),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['oog_location.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='a company group that owns many subsidiaries'
    )
    op.create_table('oog_product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('cpn', sa.String(length=50), nullable=True, comment='customer part number'),
    sa.Column('proj', sa.String(length=50), nullable=True, comment='customer project'),
    sa.Column('pn', sa.String(length=50), nullable=True, comment='part number'),
    sa.Column('semi_pn', sa.String(length=100), nullable=True, comment='semi product part number'),
    sa.Column('detail_info', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['oog_customer.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='include semi-prodcut'
    )
    op.create_table('oog_shipping_site',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True, comment='the company you should send the bill to'),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('name_eng', sa.String(length=100), nullable=True),
    sa.Column('name_chn', sa.String(length=100), nullable=True, comment='maybe there is no chinese name, just let it equals to english name'),
    sa.ForeignKeyConstraint(['company_id'], ['oog_company.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['oog_customer.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['oog_location.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='a customer may have may sites to receive you products'
    )
    op.add_column('oog_plant_district', sa.Column('company', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'oog_plant_district', 'oog_company', ['company'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'oog_plant_district', type_='foreignkey')
    op.drop_column('oog_plant_district', 'company')
    op.drop_table('oog_shipping_site')
    op.drop_table('oog_product')
    op.drop_table('oog_company')
    op.drop_table('oog_customer')
    # ### end Alembic commands ###
