"""update supplierPOD class

Revision ID: 1fe2aa0bc90e
Revises: a81b523c19eb
Create Date: 2025-02-02 15:23:49.043854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fe2aa0bc90e'
down_revision = 'a81b523c19eb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oog_supplier_pod', sa.Column('company_id', sa.Integer(), nullable=True))
    op.drop_constraint('sys_c0011019', 'oog_supplier_pod', type_='foreignkey')
    op.create_foreign_key(None, 'oog_supplier_pod', 'oog_company', ['company_id'], ['id'])
    op.drop_column('oog_supplier_pod', 'location_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oog_supplier_pod', sa.Column('location_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'oog_supplier_pod', type_='foreignkey')
    op.create_foreign_key('sys_c0011019', 'oog_supplier_pod', 'oog_location', ['location_id'], ['id'])
    op.drop_column('oog_supplier_pod', 'company_id')
    # ### end Alembic commands ###
