"""update some table

Revision ID: 237c11aabb9f
Revises: 8feeea1a661f
Create Date: 2025-01-19 19:49:03.702160

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import oracle

# revision identifiers, used by Alembic.
revision = '237c11aabb9f'
down_revision = '8feeea1a661f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oog_sproc_material',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_dt', sa.DateTime(), nullable=True),
    sa.Column('updated_dt', sa.DateTime(), nullable=True),
    sa.Column('created_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_user_id', sa.Integer(), nullable=True),
    sa.Column('pn_layer_sproc_id', sa.Integer(), nullable=True),
    sa.Column('material_id', sa.Integer(), nullable=True),
    sa.Column('qpa', sa.Float(), nullable=True, comment='Quantity Per Assembly (pcs base, like SH/PCS, SF/PCS, KG/PCS)'),
    sa.ForeignKeyConstraint(['created_user_id'], ['oog_user.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['oog_material.id'], ),
    sa.ForeignKeyConstraint(['pn_layer_sproc_id'], ['oog_pn_layer_sproc.id'], ),
    sa.ForeignKeyConstraint(['updated_user_id'], ['oog_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Material usage in sub-processes'
    )
    op.drop_table('oog_audit_log')
    op.drop_table('oog_menu_permission')
    op.drop_table('oog_menu_item')
    op.add_column('oog_material', sa.Column('supplier_pod_id', sa.Integer(), nullable=True))
    op.drop_constraint('sys_c0011275', 'oog_material', type_='foreignkey')
    op.create_foreign_key(None, 'oog_material', 'oog_supplier_pod', ['supplier_pod_id'], ['id'])
    op.drop_column('oog_material', 'supplier_id')
    op.add_column('oog_supplier_pod', sa.Column('supplier_pod_id', sa.Integer(), nullable=True))
    op.drop_constraint('sys_c0011020', 'oog_supplier_pod', type_='foreignkey')
    op.create_foreign_key(None, 'oog_supplier_pod', 'oog_supplier_pod', ['supplier_pod_id'], ['id'])
    op.drop_column('oog_supplier_pod', 'supplier_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oog_supplier_pod', sa.Column('supplier_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'oog_supplier_pod', type_='foreignkey')
    op.create_foreign_key('sys_c0011020', 'oog_supplier_pod', 'oog_supplier', ['supplier_id'], ['id'])
    op.drop_column('oog_supplier_pod', 'supplier_pod_id')
    op.add_column('oog_material', sa.Column('supplier_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'oog_material', type_='foreignkey')
    op.create_foreign_key('sys_c0011275', 'oog_material', 'oog_supplier', ['supplier_id'], ['id'])
    op.drop_column('oog_material', 'supplier_pod_id')
    op.create_table('oog_menu_item',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_dt', oracle.DATE(), nullable=True),
    sa.Column('updated_dt', oracle.DATE(), nullable=True),
    sa.Column('created_user_id', sa.INTEGER(), nullable=True),
    sa.Column('updated_user_id', sa.INTEGER(), nullable=True),
    sa.Column('name', sa.VARCHAR(length=50), nullable=True, comment='menu item name'),
    sa.Column('icon', sa.VARCHAR(length=50), nullable=True, comment='optional icon class'),
    sa.Column('route', sa.VARCHAR(length=100), nullable=True, comment='route path'),
    sa.Column('order', sa.INTEGER(), nullable=True, comment='display order'),
    sa.Column('parent_id', sa.INTEGER(), nullable=True, comment='foreign key to parent menu item'),
    sa.Column('is_active', sa.INTEGER(), nullable=True, comment='controls visibility'),
    sa.ForeignKeyConstraint(['created_user_id'], ['oog_user.id'], name='sys_c0011220'),
    sa.ForeignKeyConstraint(['parent_id'], ['oog_menu_item.id'], name='sys_c0011221'),
    sa.ForeignKeyConstraint(['updated_user_id'], ['oog_user.id'], name='sys_c0011222'),
    sa.PrimaryKeyConstraint('id', name='sys_c0011219'),
    comment='Represents a single menu item in the hierarchical menu system'
    )
    op.create_table('oog_menu_permission',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_dt', oracle.DATE(), nullable=True),
    sa.Column('updated_dt', oracle.DATE(), nullable=True),
    sa.Column('created_user_id', sa.INTEGER(), nullable=True),
    sa.Column('updated_user_id', sa.INTEGER(), nullable=True),
    sa.Column('menu_item_id', sa.INTEGER(), nullable=True),
    sa.Column('permission_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['created_user_id'], ['oog_user.id'], name='sys_c0011238'),
    sa.ForeignKeyConstraint(['menu_item_id'], ['oog_menu_item.id'], name='sys_c0011239'),
    sa.ForeignKeyConstraint(['permission_id'], ['oog_permission.id'], name='sys_c0011240'),
    sa.ForeignKeyConstraint(['updated_user_id'], ['oog_user.id'], name='sys_c0011241'),
    sa.PrimaryKeyConstraint('id', name='sys_c0011237'),
    comment='Links menu items to permissions'
    )
    
    op.create_table('oog_audit_log',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_dt', oracle.DATE(), nullable=True),
    sa.Column('updated_dt', oracle.DATE(), nullable=True),
    sa.Column('created_user_id', sa.INTEGER(), nullable=True),
    sa.Column('updated_user_id', sa.INTEGER(), nullable=True),
    sa.Column('action', sa.VARCHAR(length=50), nullable=True),
    sa.Column('details', sa.CLOB(), nullable=True),
    sa.Column('timestamp', oracle.DATE(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['created_user_id'], ['oog_user.id'], name='sys_c0011215'),
    sa.ForeignKeyConstraint(['updated_user_id'], ['oog_user.id'], name='sys_c0011216'),
    sa.ForeignKeyConstraint(['user_id'], ['oog_user.id'], name='sys_c0011217'),
    sa.PrimaryKeyConstraint('id', name='sys_c0011214')
    )
    op.drop_table('oog_sproc_material')
    # ### end Alembic commands ###
