"""update some models

Revision ID: 3296fa77e86f
Revises: 82b92e4d10f8
Create Date: 2025-02-02 11:46:36.717676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3296fa77e86f'
down_revision = '82b92e4d10f8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('oog_company', 'name_chn', existing_type=sa.String(length=255), nullable=False)
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('oog_company', 'name_chn', existing_type=sa.String(length=255), nullable=False)
    # ### end Alembic commands ###
