"""change field name

Revision ID: 3e2204759796
Revises: 6a4de6a91e9f
Create Date: 2025-02-09 23:15:51.634414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e2204759796'
down_revision = '6a4de6a91e9f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oog_side_bar_menu', sa.Column('menu_order', sa.Integer(), nullable=True))
    op.drop_column('oog_side_bar_menu', 'order')
    op.add_column('oog_top_bar_menu', sa.Column('menu_order', sa.Integer(), nullable=True))
    op.drop_column('oog_top_bar_menu', 'order')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oog_top_bar_menu', sa.Column('order', sa.INTEGER(), nullable=True))
    op.drop_column('oog_top_bar_menu', 'menu_order')
    op.add_column('oog_side_bar_menu', sa.Column('order', sa.INTEGER(), nullable=True))
    op.drop_column('oog_side_bar_menu', 'menu_order')
    # ### end Alembic commands ###
