"""update some table

Revision ID: 46a6c4bb6309
Revises: 5a52684fc441
Create Date: 2025-01-19 21:56:44.353312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46a6c4bb6309'
down_revision = '5a52684fc441'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
