"""update some models

Revision ID: 486e7d1f9cfc
Revises: fd3ebd918428
Create Date: 2025-02-02 11:41:13.491356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '486e7d1f9cfc'
down_revision = 'fd3ebd918428'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oog_bg', sa.Column('name_chn_abbr', sa.String(length=10), nullable=True, comment='Abbreviation of the BG name'))
    op.add_column('oog_bu', sa.Column('name_chn_abbr', sa.String(length=10), nullable=True, comment='Abbreviation of the BU name'))
    op.add_column('oog_company', sa.Column('name_chn_abbr', sa.String(length=10), nullable=True, comment='Abbreviation of the company name'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('oog_company', 'name_chn_abbr')
    op.drop_column('oog_bu', 'name_chn_abbr')
    op.drop_column('oog_bg', 'name_chn_abbr')
    # ### end Alembic commands ###
