"""update some models

Revision ID: 5b52412b657e
Revises: 3296fa77e86f
Create Date: 2025-02-02 12:34:21.656373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b52412b657e'
down_revision = '3296fa77e86f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('oog_bg', 'name_chn_abbr')
    op.drop_column('oog_bu', 'name_chn_abbr')
    op.alter_column('oog_company', 'name_chn',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               existing_comment='If there is no Chinese name, it will default to the English name.')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('oog_company', 'name_chn',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               existing_comment='If there is no Chinese name, it will default to the English name.')
    op.add_column('oog_bu', sa.Column('name_chn_abbr', sa.VARCHAR(length=10), nullable=True, comment='Abbreviation of the BU name'))
    op.add_column('oog_bg', sa.Column('name_chn_abbr', sa.VARCHAR(length=10), nullable=True, comment='Abbreviation of the BG name'))
    # ### end Alembic commands ###
