"""add some tables

Revision ID: 5b60e61778da
Revises: 24c02226b72e
Create Date: 2024-12-24 22:25:30.616862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b60e61778da'
down_revision = '24c02226b72e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oog_asset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=True),
    sa.Column('num', sa.String(length=100), nullable=True),
    sa.Column('tmp_num', sa.String(length=100), nullable=True),
    sa.Column('assert_name', sa.String(length=100), nullable=True),
    sa.Column('original_price', sa.Float(), nullable=True),
    sa.Column('op_currency', sa.String(length=10), nullable=True, comment='currency of original price'),
    sa.Column('op_date', sa.Date(), nullable=True, comment='date of original price'),
    sa.Column('acquisition_price', sa.Float(), nullable=True),
    sa.Column('ap_currency', sa.String(length=10), nullable=True, comment='currency of acquisition price'),
    sa.Column('ap_date', sa.Date(), nullable=True, comment='date of acquisition price'),
    sa.ForeignKeyConstraint(['machine_id'], ['oog_machine.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('oog_asset')
    # ### end Alembic commands ###
