"""correct some error in SupplierPOD class

Revision ID: 72b7fad92f97
Revises: 8edfcbe06fca
Create Date: 2025-02-02 16:41:41.032055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72b7fad92f97'
down_revision = '8edfcbe06fca'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
