"""update some models

Revision ID: 82b92e4d10f8
Revises: f4244c41183c
Create Date: 2025-02-02 11:45:31.210331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82b92e4d10f8'
down_revision = 'f4244c41183c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
