"""add some comment to tables

Revision ID: 8900d94366d0
Revises: 99adcda7b53f
Create Date: 2024-12-24 22:55:15.220276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8900d94366d0'
down_revision = '99adcda7b53f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('oog_bg', 'name_chn',
               existing_type=sa.VARCHAR(length=50),
               comment='maybe there is no chinese name, just let it equals to english name',
               existing_nullable=True)
    op.alter_column('oog_bu', 'name_chn',
               existing_type=sa.VARCHAR(length=50),
               comment='maybe there is no chinese name, just let it equals to english name',
               existing_nullable=True)
    op.alter_column('oog_plant', 'plant_code',
               existing_type=sa.VARCHAR(length=10),
               comment='like SA03, QA08 etc.',
               existing_nullable=True)
    op.alter_column('oog_supplier', 'name_chn',
               existing_type=sa.VARCHAR(length=100),
               comment='maybe there is no chinese name, just let it equals to english name',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('oog_supplier', 'name_chn',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='maybe there is no chinese name, just let it equals to english name',
               existing_nullable=True)
    op.alter_column('oog_plant', 'plant_code',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='like SA03, QA08 etc.',
               existing_nullable=True)
    op.alter_column('oog_bu', 'name_chn',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='maybe there is no chinese name, just let it equals to english name',
               existing_nullable=True)
    op.alter_column('oog_bg', 'name_chn',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='maybe there is no chinese name, just let it equals to english name',
               existing_nullable=True)
    # ### end Alembic commands ###
