"""correct some error in SupplierPOD class

Revision ID: 8edfcbe06fca
Revises: 1fe2aa0bc90e
Create Date: 2025-02-02 16:41:20.667129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8edfcbe06fca'
down_revision = '1fe2aa0bc90e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oog_supplier_pod', sa.Column('supplier_id', sa.Integer(), nullable=True))
    op.drop_constraint('sys_c0011297', 'oog_supplier_pod', type_='foreignkey')
    op.create_foreign_key(None, 'oog_supplier_pod', 'oog_supplier', ['supplier_id'], ['id'])
    op.drop_column('oog_supplier_pod', 'supplier_pod_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oog_supplier_pod', sa.Column('supplier_pod_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'oog_supplier_pod', type_='foreignkey')
    op.create_foreign_key('sys_c0011297', 'oog_supplier_pod', 'oog_supplier_pod', ['supplier_pod_id'], ['id'])
    op.drop_column('oog_supplier_pod', 'supplier_id')
    # ### end Alembic commands ###
