"""update some table

Revision ID: 8feeea1a661f
Revises: 4464e3cdf26d
Create Date: 2025-01-19 18:44:50.639868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8feeea1a661f'
down_revision = '4464e3cdf26d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oog_material',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_dt', sa.DateTime(), nullable=True),
    sa.Column('updated_dt', sa.DateTime(), nullable=True),
    sa.Column('created_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_user_id', sa.Integer(), nullable=True),
    sa.Column('mpn', sa.String(length=20), nullable=True, comment='Material part number'),
    sa.Column('mtype', sa.String(length=10), nullable=True, comment='Material type'),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('mdesc', sa.String(length=50), nullable=True, comment='Material description'),
    sa.Column('munit', sa.String(length=10), nullable=True, comment='Material unit'),
    sa.ForeignKeyConstraint(['created_user_id'], ['oog_user.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['oog_supplier.id'], ),
    sa.ForeignKeyConstraint(['updated_user_id'], ['oog_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Material information'
    )
    op.alter_column('oog_bg', 'name_chn',
               existing_type=sa.VARCHAR(length=50),
               comment='If there is no Chinese name, it will default to the English name.',
               existing_comment='maybe there is no chinese name, just let it equals to english name',
               existing_nullable=True)
    op.alter_column('oog_bu', 'name_chn',
               existing_type=sa.VARCHAR(length=50),
               comment='If there is no Chinese name, it will default to the English name.',
               existing_comment='maybe there is no chinese name, just let it equals to english name',
               existing_nullable=True)
    op.alter_column('oog_company', 'name_chn',
               existing_type=sa.VARCHAR(length=50),
               comment='If there is no Chinese name, it will default to the English name.',
               existing_comment='maybe there is no chinese name, just let it equals to english name',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('oog_company', 'name_chn',
               existing_type=sa.VARCHAR(length=50),
               comment='maybe there is no chinese name, just let it equals to english name',
               existing_comment='If there is no Chinese name, it will default to the English name.',
               existing_nullable=True)
    op.alter_column('oog_bu', 'name_chn',
               existing_type=sa.VARCHAR(length=50),
               comment='maybe there is no chinese name, just let it equals to english name',
               existing_comment='If there is no Chinese name, it will default to the English name.',
               existing_nullable=True)
    op.alter_column('oog_bg', 'name_chn',
               existing_type=sa.VARCHAR(length=50),
               comment='maybe there is no chinese name, just let it equals to english name',
               existing_comment='If there is no Chinese name, it will default to the English name.',
               existing_nullable=True)
    op.drop_table('oog_material')
    # ### end Alembic commands ###
