"""update datatable

Revision ID: 9b1e6809d1b8
Revises: 05f490c80f7c
Create Date: 2025-01-12 00:25:43.386680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b1e6809d1b8'
down_revision = '05f490c80f7c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oog_asset', sa.Column('asset_name', sa.String(length=100), nullable=True))
    op.drop_column('oog_asset', 'assert_name')
    op.add_column('oog_plant_district', sa.Column('company_id', sa.Integer(), nullable=True))
    op.drop_constraint('sys_c0011058', 'oog_plant_district', type_='foreignkey')
    op.create_foreign_key(None, 'oog_plant_district', 'oog_company', ['company_id'], ['id'])
    op.drop_column('oog_plant_district', 'company')
    op.create_table_comment(
        'oog_supplier',
        'not only machine suppliers, but also material suppliers, out outsourcing suppliers etc.',
        existing_comment='not only machine suppliers, but also material suppliers, outourcing suppliers etc.',
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'oog_supplier',
        'not only machine suppliers, but also material suppliers, outourcing suppliers etc.',
        existing_comment='not only machine suppliers, but also material suppliers, out outsourcing suppliers etc.',
        schema=None
    )
    op.add_column('oog_plant_district', sa.Column('company', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'oog_plant_district', type_='foreignkey')
    op.create_foreign_key('sys_c0011058', 'oog_plant_district', 'oog_company', ['company'], ['id'])
    op.drop_column('oog_plant_district', 'company_id')
    op.add_column('oog_asset', sa.Column('assert_name', sa.VARCHAR(length=100), nullable=True))
    op.drop_column('oog_asset', 'asset_name')
    # ### end Alembic commands ###
