"""remove location in PlantDistrict

Revision ID: a81b523c19eb
Revises: 5b52412b657e
Create Date: 2025-02-02 13:17:02.949250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a81b523c19eb'
down_revision = '5b52412b657e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('sys_c0011002', 'oog_plant_district', type_='foreignkey')
    op.drop_column('oog_plant_district', 'location_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oog_plant_district', sa.Column('location_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key('sys_c0011002', 'oog_plant_district', 'oog_location', ['location_id'], ['id'])
    # ### end Alembic commands ###
