"""add new column to Location

Revision ID: ad9762760f96
Revises: 57d8c92ddd75
Create Date: 2025-02-01 21:20:07.911638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad9762760f96'
down_revision = '57d8c92ddd75'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oog_location', sa.Column('region', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('oog_location', 'region')
    # ### end Alembic commands ###
