"""add PDBUProduct model

Revision ID: d2744cf123ff
Revises: 9b1e6809d1b8
Create Date: 2025-01-16 23:28:00.634374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2744cf123ff'
down_revision = '9b1e6809d1b8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oog_pdbu_product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rpn', sa.String(length=50), nullable=True),
    sa.Column('detial_info', sa.Text(), nullable=True),
    sa.Column('ignore_validate_rpn', sa.Boolean(), nullable=True),
    sa.Column('bu_id', sa.Integer(), nullable=True),
    sa.Column('plant_district_id', sa.Integer(), nullable=True),
    sa.Column('master_product_id', sa.Integer(), nullable=True),
    sa.Column('sub_product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bu_id'], ['oog_bu.id'], ),
    sa.ForeignKeyConstraint(['master_product_id'], ['oog_product.id'], ),
    sa.ForeignKeyConstraint(['plant_district_id'], ['oog_plant_district.id'], ),
    sa.ForeignKeyConstraint(['sub_product_id'], ['oog_product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('oog_product_share_ver',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product1_id', sa.Integer(), nullable=True),
    sa.Column('product2_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product1_id'], ['oog_product.id'], ),
    sa.ForeignKeyConstraint(['product2_id'], ['oog_product.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='share version between products'
    )
    op.alter_column('oog_asset', 'num',
               existing_type=sa.VARCHAR(length=100),
               comment='there is anoter test comment',
               existing_nullable=True)
    op.drop_constraint('sys_c0011049', 'oog_company', type_='foreignkey')
    op.drop_column('oog_company', 'location_id')
    op.add_column('oog_product', sa.Column('virtual', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('oog_product', 'virtual')
    op.add_column('oog_company', sa.Column('location_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key('sys_c0011049', 'oog_company', 'oog_location', ['location_id'], ['id'])
    op.alter_column('oog_asset', 'num',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='there is anoter test comment',
               existing_nullable=True)
    op.drop_table('oog_product_share_ver')
    op.drop_table('oog_pdbu_product')
    # ### end Alembic commands ###
