"""add some comment to tables

Revision ID: ec307408f1ef
Revises: fc0d483e1ff7
Create Date: 2024-12-24 22:49:01.995011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec307408f1ef'
down_revision = 'fc0d483e1ff7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'oog_currency_ex',
        'currency exchange rate data',
        existing_comment=None,
        schema=None
    )
    op.alter_column('oog_plant', 'bu_id',
               existing_type=sa.INTEGER(),
               comment='may be one building owned by multi bus. like part of SA02 is owned by FPC and the left part is owned by HDI.',
               existing_nullable=True)
    op.create_table_comment(
        'oog_plant',
        'specific building of a factory. like SA03, SA02',
        existing_comment=None,
        schema=None
    )
    op.alter_column('oog_supplier', 'region',
               existing_type=sa.VARCHAR(length=200),
               comment='the localtion of headquarters. like China HK, China Taiwan, Japan etc.',
               existing_nullable=True)
    op.create_table_comment(
        'oog_supplier',
        'not only machine suppliers, but also material suppliers, outourcing suppliers etc.',
        existing_comment=None,
        schema=None
    )
    op.create_table_comment(
        'oog_supplier_pod',
        'POD: Place Of Delivery. A supplier many have many place to delivery the products.',
        existing_comment=None,
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table_comment(
        'oog_supplier_pod',
        existing_comment='POD: Place Of Delivery. A supplier many have many place to delivery the products.',
        schema=None
    )
    op.drop_table_comment(
        'oog_supplier',
        existing_comment='not only machine suppliers, but also material suppliers, outourcing suppliers etc.',
        schema=None
    )
    op.alter_column('oog_supplier', 'region',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='the localtion of headquarters. like China HK, China Taiwan, Japan etc.',
               existing_nullable=True)
    op.drop_table_comment(
        'oog_plant',
        existing_comment='specific building of a factory. like SA03, SA02',
        schema=None
    )
    op.alter_column('oog_plant', 'bu_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='may be one building owned by multi bus. like part of SA02 is owned by FPC and the left part is owned by HDI.',
               existing_nullable=True)
    op.drop_table_comment(
        'oog_currency_ex',
        existing_comment='currency exchange rate data',
        schema=None
    )
    # ### end Alembic commands ###
