"""update some tables

Revision ID: f1ac94082896
Revises: 46a6c4bb6309
Create Date: 2025-01-20 00:03:04.932913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1ac94082896'
down_revision = '46a6c4bb6309'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oog_user', sa.Column('password_hash', sa.String(length=255), nullable=False))
    op.drop_column('oog_user', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oog_user', sa.Column('password', sa.VARCHAR(length=255), nullable=False))
    op.drop_column('oog_user', 'password_hash')
    # ### end Alembic commands ###
