"""update some models

Revision ID: f4244c41183c
Revises: 486e7d1f9cfc
Create Date: 2025-02-02 11:43:36.349211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4244c41183c'
down_revision = '486e7d1f9cfc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
