"""update menu sys2

Revision ID: fd3ebd918428
Revises: 3b6954efd35e
Create Date: 2025-02-02 10:32:29.598927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd3ebd918428'
down_revision = '3b6954efd35e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
