"""add BG

Revision ID: 303fe5ae496b
Revises: cdcb5494e80e
Create Date: 2024-12-20 21:23:07.963842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '303fe5ae496b'
down_revision = 'cdcb5494e80e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oog_bg',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_eng', sa.String(length=50), nullable=True),
    sa.Column('name_chn', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('oog_bg')
    # ### end Alembic commands ###
