"""add another name to Task

Revision ID: 3300d5fc2e6d
Revises: 57c82ef0c3af
Create Date: 2024-12-18 22:18:36.965199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3300d5fc2e6d'
down_revision = '57c82ef0c3af'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('othername', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'othername')
    # ### end Alembic commands ###
