"""add created_user and updated_user fields to User model

Revision ID: 4464e3cdf26d
Revises: 21275f5cdfd1
Create Date: 2025-01-18 00:54:06.191434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4464e3cdf26d'
down_revision = '21275f5cdfd1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oog_user', sa.Column('created_user_id', sa.Integer(), nullable=True))
    op.add_column('oog_user', sa.Column('updated_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'oog_user', 'oog_user', ['created_user_id'], ['id'])
    op.create_foreign_key(None, 'oog_user', 'oog_user', ['updated_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'oog_user', type_='foreignkey')
    op.drop_constraint(None, 'oog_user', type_='foreignkey')
    op.drop_column('oog_user', 'updated_user_id')
    op.drop_column('oog_user', 'created_user_id')
    # ### end Alembic commands ###
