"""update some table

Revision ID: 5a52684fc441
Revises: 7dd2331f36ff
Create Date: 2025-01-19 21:18:18.534263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a52684fc441'
down_revision = '7dd2331f36ff'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
