"""update some table

Revision ID: 7dd2331f36ff
Revises: 237c11aabb9f
Create Date: 2025-01-19 20:46:36.455355

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import oracle

# revision identifiers, used by Alembic.
revision = '7dd2331f36ff'
down_revision = '237c11aabb9f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('oog_user_session')
    op.add_column('oog_user', sa.Column('is_admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('oog_user', 'is_admin')
    op.create_table('oog_user_session',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_dt', oracle.DATE(), nullable=True),
    sa.Column('updated_dt', oracle.DATE(), nullable=True),
    sa.Column('created_user_id', sa.INTEGER(), nullable=True),
    sa.Column('updated_user_id', sa.INTEGER(), nullable=True),
    sa.Column('session_created_dt', oracle.DATE(), nullable=True),
    sa.Column('session_expires_dt', oracle.DATE(), nullable=True),
    sa.Column('last_activity', oracle.DATE(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['created_user_id'], ['oog_user.id'], name='sys_c0011233'),
    sa.ForeignKeyConstraint(['updated_user_id'], ['oog_user.id'], name='sys_c0011234'),
    sa.ForeignKeyConstraint(['user_id'], ['oog_user.id'], name='sys_c0011235'),
    sa.PrimaryKeyConstraint('id', name='sys_c0011232')
    )
    # ### end Alembic commands ###
