"""add some table

Revision ID: 94a659f5968c
Revises: 1b56c358f970
Create Date: 2024-12-20 23:13:39.007085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94a659f5968c'
down_revision = '1b56c358f970'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oog_location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('province', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('street', sa.String(length=200), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('oog_bu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_eng', sa.String(length=50), nullable=True),
    sa.Column('name_chn', sa.String(length=50), nullable=True),
    sa.Column('bg_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bg_id'], ['oog_bg.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('oog_plant_district',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_eng', sa.String(length=50), nullable=True),
    sa.Column('name_chn', sa.String(length=50), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['oog_location.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('oog_plant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plant_code', sa.String(length=10), nullable=True),
    sa.Column('plant_district_id', sa.Integer(), nullable=True),
    sa.Column('bu_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bu_id'], ['oog_bu.id'], ),
    sa.ForeignKeyConstraint(['plant_district_id'], ['oog_plant_district.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('oog_plant')
    op.drop_table('oog_plant_district')
    op.drop_table('oog_bu')
    op.drop_table('oog_location')
    # ### end Alembic commands ###
