"""add some comment to tables

Revision ID: 99adcda7b53f
Revises: ec307408f1ef
Create Date: 2024-12-24 22:52:16.278630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99adcda7b53f'
down_revision = 'ec307408f1ef'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'oog_bg',
        'Business Group. BG1, BG2, BG3 etc',
        existing_comment=None,
        schema=None
    )
    op.create_table_comment(
        'oog_bu',
        'Business Unit. HDI, FPC, MSAP, RPCB, BTK etc',
        existing_comment=None,
        schema=None
    )
    op.create_table_comment(
        'oog_plant_district',
        'the place where many plants located. like SA, SB, HA, HB, QA etc.',
        existing_comment=None,
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table_comment(
        'oog_plant_district',
        existing_comment='the place where many plants located. like SA, SB, HA, HB, QA etc.',
        schema=None
    )
    op.drop_table_comment(
        'oog_bu',
        existing_comment='Business Unit. HDI, FPC, MSAP, RPCB, BTK etc',
        schema=None
    )
    op.drop_table_comment(
        'oog_bg',
        existing_comment='Business Group. BG1, BG2, BG3 etc',
        schema=None
    )
    # ### end Alembic commands ###
