"""add some table

Revision ID: b211289f00fd
Revises: b55e5ccd9231
Create Date: 2024-12-22 17:53:21.116223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b211289f00fd'
down_revision = 'b55e5ccd9231'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oog_currency_ex',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fr_curr', sa.String(length=10), nullable=True),
    sa.Column('to_curr', sa.String(length=10), nullable=True),
    sa.Column('ex_dt', sa.DateTime(), nullable=True),
    sa.Column('ex_rate', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('oog_currency_ex')
    # ### end Alembic commands ###
