"""add some table

Revision ID: b55e5ccd9231
Revises: 94a659f5968c
Create Date: 2024-12-22 17:29:55.269220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b55e5ccd9231'
down_revision = '94a659f5968c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oog_supplier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_eng', sa.String(length=100), nullable=True),
    sa.Column('name_chn', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=200), nullable=True),
    sa.Column('web_site', sa.String(length=200), nullable=True),
    sa.Column('detail_info', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('oog_supplier_pod',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(length=100), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['oog_location.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['oog_supplier.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('oog_supplier_pod')
    op.drop_table('oog_supplier')
    # ### end Alembic commands ###
