"""delete task2

Revision ID: cdcb5494e80e
Revises: 3300d5fc2e6d
Create Date: 2024-12-19 23:51:40.316013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdcb5494e80e'
down_revision = '3300d5fc2e6d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task2')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task2',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('description', sa.VARCHAR(length=100), nullable=False),
    sa.Column('completed', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='sys_c0010984')
    )
    # ### end Alembic commands ###
